server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.60.11:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: imagrid-server
        uri: lb:http://imagrid-server
        predicates:
        - Path=/imagrid-server/**
        filters:
        - RewritePath=/imagrid-server/(?<path>.*), /$\{path}
      - id: imagrid-authent
        uri: lb:http://imagrid-authent
        predicates:
        - Path=/imagrid-authent/**
        filters:
        - RewritePath=/imagrid-authent/(?<path>.*), /$\{path}

      - id: imagrid-network
        uri: lb:http://imagrid-network
        predicates:
        - Path=/imagrid-network/**
        filters:
        - RewritePath=/imagrid-network/(?<path>.*), /$\{path}

      - id: imagrid-mapping
        uri: lb:http://imagrid-mapping
        predicates:
        - Path=/imagrid-mapping/**
        filters:
        - RewritePath=/imagrid-mapping/(?<path>.*), /$\{path}

      - id: imagrid-metrix
        uri: lb:http://imagrid-metrix
        predicates:
        - Path=/imagrid-metrix/**
        filters:
        - RewritePath=/imagrid-metrix/(?<path>.*), /$\{path}
        
      - id: imagrid-app
        uri: lb:http://imagrid-app
        predicates:
        - Path=/imagrid-app/**
        filters:
        - RewritePath=/imagrid-app/(?<path>.*), /$\{path}

        