server:
  port: 8090
  servlet:
    context-path: /
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.60.11:8061/eureka/
  instance:
    hostname: 192.168.60.15
    homePageUrlPath: ${server.servlet.context-path}    
          
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
