server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.60.11:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"   