server:
  port: ${DISCOVERY_SERVER_PORT}

eureka:
  instance:
    hostname: ${DISCOVERY_SERVER_IP}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
