server:
  port: 9080
  servlet:
    context-path: /

kafka:
  bootstrapAddress: localhost:9092

spring:
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    hostname: localhost
    port: 8061
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    